#!/bin/sh

# Use the logo/super/windows key (mod) as the primary modifier key (mod1=alt)
mod="Mod4"
mod1="Mod1"

# Repeat rate
riverctl set-repeat 50 300

# Spawn programs
riverctl map normal $mod Return spawn "$TERMINAL"
riverctl map normal $mod W spawn "$BROWSER"
riverctl map normal $mod R spawn "$TERMINAL lf"

# Reload river config
riverctl map normal $mod+Shift R spawn "~/.config/river/init"

# Close the focused window
riverctl map normal $mod Q close

# Exit river
riverctl map normal $mod+Shift Q exit

# Tiling
riverctl spawn rivertile
riverctl output-layout rivertile

# Border
riverctl border-width 4
riverctl border-color-focused 0xfaedff
riverctl border-color-unfocused 0x05080a
riverctl border-color-urgent 0xfd3a4a

# Focus view
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Switch the focused view
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Decrease/increase the main ratio of rivertile
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Toggle fullscreen and float
riverctl map normal $mod F toggle-fullscreen
riverctl map normal $mod+Shift Space toggle-float
